# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: alpa.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
    owner: "alpa-team"
    project: "alpa"
    branch: main
