# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-alpa-conf.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
      - epel-9
    metadata:
      owner: "alpa-team"
      project: "alpa-conf"
      branch: main
