# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: alpa.spec

files_to_sync:
  - alpa.spec
  - .packit.yaml

upstream_package_name: alpa
downstream_package_name: alpa

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
      - epel-9
    metadata:
      owner: "alpa-team"
      project: "alpa"
      branch: main
