# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-alpa-conf.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
    metadata:
      owner: "alpa-team"
      project: "alpa-pull-requests"
      branch: main

  - job: copr_build
    trigger: commit
    targets:
      - fedora-all
    metadata:
      owner: "alpa-team"
      project: "alpa"
      branch: main
